initrd-boot-gui: Fix xorg package move
Fixes the following evaluation error:

       error: The xorg package set has been moved to the top level.

(cherry picked from commit 2aac0f0cc8ffc82ac41be4c763a47b9c93293195)