overlay: Fix xorg package move
Fixes the following evaluation error:

       error: The xorg package set has been moved to the top level.

Co-authored-by: benaryorg <binary@benary.org>
(cherry picked from commit 9798ff89d28fa0e890e013822602f7fc546414e4)